// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.mongo;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDateTime;

@Document(collection = "user_search_logs")
public class UserSearchLog {
    @Id
    private String id;
    private String query;
    private LocalDateTime searchTime;
    private int resultCount;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class UserSearchLogBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String query;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime searchTime;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int resultCount;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        UserSearchLogBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserSearchLog.UserSearchLogBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserSearchLog.UserSearchLogBuilder query(final String query) {
            this.query = query;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserSearchLog.UserSearchLogBuilder searchTime(final LocalDateTime searchTime) {
            this.searchTime = searchTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserSearchLog.UserSearchLogBuilder resultCount(final int resultCount) {
            this.resultCount = resultCount;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserSearchLog build() {
            return new UserSearchLog(this.id, this.query, this.searchTime, this.resultCount);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "UserSearchLog.UserSearchLogBuilder(id=" + this.id + ", query=" + this.query + ", searchTime=" + this.searchTime + ", resultCount=" + this.resultCount + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static UserSearchLog.UserSearchLogBuilder builder() {
        return new UserSearchLog.UserSearchLogBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getQuery() {
        return this.query;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getSearchTime() {
        return this.searchTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getResultCount() {
        return this.resultCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuery(final String query) {
        this.query = query;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSearchTime(final LocalDateTime searchTime) {
        this.searchTime = searchTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResultCount(final int resultCount) {
        this.resultCount = resultCount;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserSearchLog)) return false;
        final UserSearchLog other = (UserSearchLog) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getResultCount() != other.getResultCount()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$query = this.getQuery();
        final java.lang.Object other$query = other.getQuery();
        if (this$query == null ? other$query != null : !this$query.equals(other$query)) return false;
        final java.lang.Object this$searchTime = this.getSearchTime();
        final java.lang.Object other$searchTime = other.getSearchTime();
        if (this$searchTime == null ? other$searchTime != null : !this$searchTime.equals(other$searchTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserSearchLog;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getResultCount();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $query = this.getQuery();
        result = result * PRIME + ($query == null ? 43 : $query.hashCode());
        final java.lang.Object $searchTime = this.getSearchTime();
        result = result * PRIME + ($searchTime == null ? 43 : $searchTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "UserSearchLog(id=" + this.getId() + ", query=" + this.getQuery() + ", searchTime=" + this.getSearchTime() + ", resultCount=" + this.getResultCount() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserSearchLog() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserSearchLog(final String id, final String query, final LocalDateTime searchTime, final int resultCount) {
        this.id = id;
        this.query = query;
        this.searchTime = searchTime;
        this.resultCount = resultCount;
    }
}
