// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.mongo;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

@Document(collection = "product_embeddings")
public class ProductEmbedding {
    @Id
    private String id;
    private Long productId; // Reference to PostgreSQL Product ID
    // We store the text that was embedded to help with context
    private String textContent;
    // The actual vector embedding
    private List<Double> embedding;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ProductEmbeddingBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long productId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String textContent;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<Double> embedding;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ProductEmbeddingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductEmbedding.ProductEmbeddingBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductEmbedding.ProductEmbeddingBuilder productId(final Long productId) {
            this.productId = productId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductEmbedding.ProductEmbeddingBuilder textContent(final String textContent) {
            this.textContent = textContent;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductEmbedding.ProductEmbeddingBuilder embedding(final List<Double> embedding) {
            this.embedding = embedding;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductEmbedding build() {
            return new ProductEmbedding(this.id, this.productId, this.textContent, this.embedding);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ProductEmbedding.ProductEmbeddingBuilder(id=" + this.id + ", productId=" + this.productId + ", textContent=" + this.textContent + ", embedding=" + this.embedding + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ProductEmbedding.ProductEmbeddingBuilder builder() {
        return new ProductEmbedding.ProductEmbeddingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getProductId() {
        return this.productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTextContent() {
        return this.textContent;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Double> getEmbedding() {
        return this.embedding;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductId(final Long productId) {
        this.productId = productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTextContent(final String textContent) {
        this.textContent = textContent;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmbedding(final List<Double> embedding) {
        this.embedding = embedding;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProductEmbedding)) return false;
        final ProductEmbedding other = (ProductEmbedding) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$productId = this.getProductId();
        final java.lang.Object other$productId = other.getProductId();
        if (this$productId == null ? other$productId != null : !this$productId.equals(other$productId)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$textContent = this.getTextContent();
        final java.lang.Object other$textContent = other.getTextContent();
        if (this$textContent == null ? other$textContent != null : !this$textContent.equals(other$textContent)) return false;
        final java.lang.Object this$embedding = this.getEmbedding();
        final java.lang.Object other$embedding = other.getEmbedding();
        if (this$embedding == null ? other$embedding != null : !this$embedding.equals(other$embedding)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProductEmbedding;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $productId = this.getProductId();
        result = result * PRIME + ($productId == null ? 43 : $productId.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $textContent = this.getTextContent();
        result = result * PRIME + ($textContent == null ? 43 : $textContent.hashCode());
        final java.lang.Object $embedding = this.getEmbedding();
        result = result * PRIME + ($embedding == null ? 43 : $embedding.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ProductEmbedding(id=" + this.getId() + ", productId=" + this.getProductId() + ", textContent=" + this.getTextContent() + ", embedding=" + this.getEmbedding() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductEmbedding() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductEmbedding(final String id, final Long productId, final String textContent, final List<Double> embedding) {
        this.id = id;
        this.productId = productId;
        this.textContent = textContent;
        this.embedding = embedding;
    }
}
