// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.mongo;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "product_descriptions")
public class ProductDescription {
    @Id
    private String id;
    private Long productId; // Reference to PostgreSQL Product ID
    private String detailedDescription;
    private String features;
    private String specifications;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ProductDescriptionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long productId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String detailedDescription;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String features;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String specifications;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ProductDescriptionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDescription.ProductDescriptionBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDescription.ProductDescriptionBuilder productId(final Long productId) {
            this.productId = productId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDescription.ProductDescriptionBuilder detailedDescription(final String detailedDescription) {
            this.detailedDescription = detailedDescription;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDescription.ProductDescriptionBuilder features(final String features) {
            this.features = features;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDescription.ProductDescriptionBuilder specifications(final String specifications) {
            this.specifications = specifications;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDescription build() {
            return new ProductDescription(this.id, this.productId, this.detailedDescription, this.features, this.specifications);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ProductDescription.ProductDescriptionBuilder(id=" + this.id + ", productId=" + this.productId + ", detailedDescription=" + this.detailedDescription + ", features=" + this.features + ", specifications=" + this.specifications + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ProductDescription.ProductDescriptionBuilder builder() {
        return new ProductDescription.ProductDescriptionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getProductId() {
        return this.productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDetailedDescription() {
        return this.detailedDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFeatures() {
        return this.features;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSpecifications() {
        return this.specifications;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductId(final Long productId) {
        this.productId = productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDetailedDescription(final String detailedDescription) {
        this.detailedDescription = detailedDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFeatures(final String features) {
        this.features = features;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecifications(final String specifications) {
        this.specifications = specifications;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProductDescription)) return false;
        final ProductDescription other = (ProductDescription) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$productId = this.getProductId();
        final java.lang.Object other$productId = other.getProductId();
        if (this$productId == null ? other$productId != null : !this$productId.equals(other$productId)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$detailedDescription = this.getDetailedDescription();
        final java.lang.Object other$detailedDescription = other.getDetailedDescription();
        if (this$detailedDescription == null ? other$detailedDescription != null : !this$detailedDescription.equals(other$detailedDescription)) return false;
        final java.lang.Object this$features = this.getFeatures();
        final java.lang.Object other$features = other.getFeatures();
        if (this$features == null ? other$features != null : !this$features.equals(other$features)) return false;
        final java.lang.Object this$specifications = this.getSpecifications();
        final java.lang.Object other$specifications = other.getSpecifications();
        if (this$specifications == null ? other$specifications != null : !this$specifications.equals(other$specifications)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProductDescription;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $productId = this.getProductId();
        result = result * PRIME + ($productId == null ? 43 : $productId.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $detailedDescription = this.getDetailedDescription();
        result = result * PRIME + ($detailedDescription == null ? 43 : $detailedDescription.hashCode());
        final java.lang.Object $features = this.getFeatures();
        result = result * PRIME + ($features == null ? 43 : $features.hashCode());
        final java.lang.Object $specifications = this.getSpecifications();
        result = result * PRIME + ($specifications == null ? 43 : $specifications.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ProductDescription(id=" + this.getId() + ", productId=" + this.getProductId() + ", detailedDescription=" + this.getDetailedDescription() + ", features=" + this.getFeatures() + ", specifications=" + this.getSpecifications() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductDescription() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductDescription(final String id, final Long productId, final String detailedDescription, final String features, final String specifications) {
        this.id = id;
        this.productId = productId;
        this.detailedDescription = detailedDescription;
        this.features = features;
        this.specifications = specifications;
    }
}
