// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "inventory")
public class Inventory {
    @Id
    private Long productId;
    @OneToOne
    @MapsId
    @JoinColumn(name = "product_id")
    private Product product;
    @Column(nullable = false)
    private Integer stockQuantity;
    private String warehouseLocation;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class InventoryBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long productId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Product product;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer stockQuantity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String warehouseLocation;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        InventoryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Inventory.InventoryBuilder productId(final Long productId) {
            this.productId = productId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Inventory.InventoryBuilder product(final Product product) {
            this.product = product;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Inventory.InventoryBuilder stockQuantity(final Integer stockQuantity) {
            this.stockQuantity = stockQuantity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Inventory.InventoryBuilder warehouseLocation(final String warehouseLocation) {
            this.warehouseLocation = warehouseLocation;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Inventory build() {
            return new Inventory(this.productId, this.product, this.stockQuantity, this.warehouseLocation);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Inventory.InventoryBuilder(productId=" + this.productId + ", product=" + this.product + ", stockQuantity=" + this.stockQuantity + ", warehouseLocation=" + this.warehouseLocation + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Inventory.InventoryBuilder builder() {
        return new Inventory.InventoryBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getProductId() {
        return this.productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStockQuantity() {
        return this.stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWarehouseLocation() {
        return this.warehouseLocation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductId(final Long productId) {
        this.productId = productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProduct(final Product product) {
        this.product = product;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStockQuantity(final Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWarehouseLocation(final String warehouseLocation) {
        this.warehouseLocation = warehouseLocation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Inventory() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Inventory(final Long productId, final Product product, final Integer stockQuantity, final String warehouseLocation) {
        this.productId = productId;
        this.product = product;
        this.stockQuantity = stockQuantity;
        this.warehouseLocation = warehouseLocation;
    }
}
