// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.controller;

import com.productcatalog.app.dto.SearchRequestDTO;
import com.productcatalog.app.service.ProductSearchService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.bson.Document;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/search")
@Tag(name = "Semantic Search API", description = "MongoDB Vector Search Endpoint")
public class SearchController {
    private final ProductSearchService productSearchService;

    @Operation(summary = "Perform semantic search using MongoDB Atlas Vector Search")
    @PostMapping
    public ResponseEntity<List<Document>> semanticSearch(@Valid @RequestBody SearchRequestDTO requestDTO) {
        return ResponseEntity.ok(productSearchService.semanticSearch(requestDTO));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SearchController(final ProductSearchService productSearchService) {
        this.productSearchService = productSearchService;
    }
}
