// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.dto;

import java.math.BigDecimal;

public class ProductDTO {
    private Long id;
    private String name;
    private String brand;
    private String sku;
    private String imageUrl;
    private Long categoryId;
    private String categoryName;
    private BigDecimal basePrice;
    private BigDecimal discountPrice;
    private String currency;
    private Integer stockQuantity;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ProductDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String brand;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String sku;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long categoryId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String categoryName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal basePrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal discountPrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String currency;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer stockQuantity;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ProductDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder brand(final String brand) {
            this.brand = brand;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder sku(final String sku) {
            this.sku = sku;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder categoryId(final Long categoryId) {
            this.categoryId = categoryId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder categoryName(final String categoryName) {
            this.categoryName = categoryName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder basePrice(final BigDecimal basePrice) {
            this.basePrice = basePrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder discountPrice(final BigDecimal discountPrice) {
            this.discountPrice = discountPrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO.ProductDTOBuilder stockQuantity(final Integer stockQuantity) {
            this.stockQuantity = stockQuantity;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDTO build() {
            return new ProductDTO(this.id, this.name, this.brand, this.sku, this.categoryId, this.categoryName, this.basePrice, this.discountPrice, this.currency, this.stockQuantity);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ProductDTO.ProductDTOBuilder(id=" + this.id + ", name=" + this.name + ", brand=" + this.brand + ", sku=" + this.sku + ", categoryId=" + this.categoryId + ", categoryName=" + this.categoryName + ", basePrice=" + this.basePrice + ", discountPrice=" + this.discountPrice + ", currency=" + this.currency + ", stockQuantity=" + this.stockQuantity + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ProductDTO.ProductDTOBuilder builder() {
        return new ProductDTO.ProductDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBrand() {
        return this.brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSku() {
        return this.sku;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategoryName() {
        return this.categoryName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDiscountPrice() {
        return this.discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStockQuantity() {
        return this.stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBrand(final String brand) {
        this.brand = brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSku(final String sku) {
        this.sku = sku;
    }

    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryId(final Long categoryId) {
        this.categoryId = categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryName(final String categoryName) {
        this.categoryName = categoryName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBasePrice(final BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiscountPrice(final BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStockQuantity(final Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProductDTO)) return false;
        final ProductDTO other = (ProductDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$categoryId = this.getCategoryId();
        final java.lang.Object other$categoryId = other.getCategoryId();
        if (this$categoryId == null ? other$categoryId != null : !this$categoryId.equals(other$categoryId)) return false;
        final java.lang.Object this$stockQuantity = this.getStockQuantity();
        final java.lang.Object other$stockQuantity = other.getStockQuantity();
        if (this$stockQuantity == null ? other$stockQuantity != null : !this$stockQuantity.equals(other$stockQuantity)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$brand = this.getBrand();
        final java.lang.Object other$brand = other.getBrand();
        if (this$brand == null ? other$brand != null : !this$brand.equals(other$brand)) return false;
        final java.lang.Object this$sku = this.getSku();
        final java.lang.Object other$sku = other.getSku();
        if (this$sku == null ? other$sku != null : !this$sku.equals(other$sku)) return false;
        final java.lang.Object this$categoryName = this.getCategoryName();
        final java.lang.Object other$categoryName = other.getCategoryName();
        if (this$categoryName == null ? other$categoryName != null : !this$categoryName.equals(other$categoryName)) return false;
        final java.lang.Object this$basePrice = this.getBasePrice();
        final java.lang.Object other$basePrice = other.getBasePrice();
        if (this$basePrice == null ? other$basePrice != null : !this$basePrice.equals(other$basePrice)) return false;
        final java.lang.Object this$discountPrice = this.getDiscountPrice();
        final java.lang.Object other$discountPrice = other.getDiscountPrice();
        if (this$discountPrice == null ? other$discountPrice != null : !this$discountPrice.equals(other$discountPrice)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProductDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $categoryId = this.getCategoryId();
        result = result * PRIME + ($categoryId == null ? 43 : $categoryId.hashCode());
        final java.lang.Object $stockQuantity = this.getStockQuantity();
        result = result * PRIME + ($stockQuantity == null ? 43 : $stockQuantity.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $brand = this.getBrand();
        result = result * PRIME + ($brand == null ? 43 : $brand.hashCode());
        final java.lang.Object $sku = this.getSku();
        result = result * PRIME + ($sku == null ? 43 : $sku.hashCode());
        final java.lang.Object $categoryName = this.getCategoryName();
        result = result * PRIME + ($categoryName == null ? 43 : $categoryName.hashCode());
        final java.lang.Object $basePrice = this.getBasePrice();
        result = result * PRIME + ($basePrice == null ? 43 : $basePrice.hashCode());
        final java.lang.Object $discountPrice = this.getDiscountPrice();
        result = result * PRIME + ($discountPrice == null ? 43 : $discountPrice.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ProductDTO(id=" + this.getId() + ", name=" + this.getName() + ", brand=" + this.getBrand() + ", sku=" + this.getSku() + ", categoryId=" + this.getCategoryId() + ", categoryName=" + this.getCategoryName() + ", basePrice=" + this.getBasePrice() + ", discountPrice=" + this.getDiscountPrice() + ", currency=" + this.getCurrency() + ", stockQuantity=" + this.getStockQuantity() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductDTO(final Long id, final String name, final String brand, final String sku, final Long categoryId, final String categoryName, final BigDecimal basePrice, final BigDecimal discountPrice, final String currency, final Integer stockQuantity) {
        this.id = id;
        this.name = name;
        this.brand = brand;
        this.sku = sku;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.basePrice = basePrice;
        this.discountPrice = discountPrice;
        this.currency = currency;
        this.stockQuantity = stockQuantity;
    }
}
