// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.dto;

import jakarta.validation.constraints.NotBlank;

public class SearchRequestDTO {
    @NotBlank(message = "Search query cannot be blank")
    private String query;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SearchRequestDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getQuery() {
        return this.query;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuery(final String query) {
        this.query = query;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SearchRequestDTO)) return false;
        final SearchRequestDTO other = (SearchRequestDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$query = this.getQuery();
        final java.lang.Object other$query = other.getQuery();
        if (this$query == null ? other$query != null : !this$query.equals(other$query)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SearchRequestDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $query = this.getQuery();
        result = result * PRIME + ($query == null ? 43 : $query.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "SearchRequestDTO(query=" + this.getQuery() + ")";
    }
}
