// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.service;

import com.productcatalog.app.dto.ProductDTO;
import com.productcatalog.app.dto.ProductDetailsDTO;
import com.productcatalog.app.dto.ProductFilterRequestDTO;
import com.productcatalog.app.entity.Product;
import com.productcatalog.app.mapper.ProductMapper;
import com.productcatalog.app.mongo.ProductDescription;
import com.productcatalog.app.mongo.ProductDescriptionRepository;
import com.productcatalog.app.repository.ProductRepository;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import jakarta.persistence.criteria.Predicate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class ProductService {
    private final ProductRepository productRepository;
    private final ProductDescriptionRepository productDescriptionRepository;
    private final ProductMapper productMapper;

    public List<ProductDTO> getAllProducts() {
        return productRepository.findAll().stream().map(productMapper::toDto).collect(Collectors.toList());
    }

    public ProductDTO getProductById(Long id) {
        Product product = productRepository.findById(id).orElseThrow(() -> new RuntimeException("Product not found with id: " + id));
        return productMapper.toDto(product);
    }

    public ProductDTO createProduct(ProductDTO productDTO) {
        Product product = productMapper.toEntity(productDTO);
        Product savedProduct = productRepository.save(product);
        return productMapper.toDto(savedProduct);
    }

    public ProductDTO updateProduct(Long id, ProductDTO productDTO) {
        Product existingProduct = productRepository.findById(id).orElseThrow(() -> new RuntimeException("Product not found with id: " + id));
        existingProduct.setName(productDTO.getName());
        existingProduct.setBrand(productDTO.getBrand());
        existingProduct.setSku(productDTO.getSku());
        if (existingProduct.getPricing() != null) {
            existingProduct.getPricing().setBasePrice(productDTO.getBasePrice());
            existingProduct.getPricing().setDiscountPrice(productDTO.getDiscountPrice());
            existingProduct.getPricing().setCurrency(productDTO.getCurrency());
        }
        if (existingProduct.getInventory() != null) {
            existingProduct.getInventory().setStockQuantity(productDTO.getStockQuantity());
        }
        Product updatedProduct = productRepository.save(existingProduct);
        return productMapper.toDto(updatedProduct);
    }

    public void deleteProduct(Long id) {
        productRepository.deleteById(id);
    }

    public List<ProductDTO> filterProducts(ProductFilterRequestDTO filter) {
        Specification<Product> spec = (root, query, cb) -> {
            List<Predicate> predicates = new ArrayList<>();
            if (filter.getCategory() != null && !filter.getCategory().isEmpty()) {
                predicates.add(cb.equal(root.get("category").get("name"), filter.getCategory()));
            }
            if (filter.getBrand() != null && !filter.getBrand().isEmpty()) {
                predicates.add(cb.equal(root.get("brand"), filter.getBrand()));
            }
            if (filter.getMinPrice() != null) {
                predicates.add(cb.greaterThanOrEqualTo(root.get("pricing").get("basePrice"), filter.getMinPrice()));
            }
            if (filter.getMaxPrice() != null) {
                predicates.add(cb.lessThanOrEqualTo(root.get("pricing").get("basePrice"), filter.getMaxPrice()));
            }
            return cb.and(predicates.toArray(new Predicate[0]));
        };
        return productRepository.findAll(spec).stream().map(productMapper::toDto).collect(Collectors.toList());
    }

    public ProductDetailsDTO getProductDetails(Long id) {
        Product product = productRepository.findById(id).orElseThrow(() -> new RuntimeException("Product not found with id: " + id));
        Optional<ProductDescription> descriptionOpt = productDescriptionRepository.findByProductId(id);
        ProductDetailsDTO details = new ProductDetailsDTO();
        details.setId(product.getId());
        details.setName(product.getName());
        details.setBrand(product.getBrand());
        details.setSku(product.getSku());
        details.setCategoryName(product.getCategory() != null ? product.getCategory().getName() : null);
        if (product.getPricing() != null) {
            details.setBasePrice(product.getPricing().getBasePrice());
            details.setDiscountPrice(product.getPricing().getDiscountPrice());
            details.setCurrency(product.getPricing().getCurrency());
        }
        if (product.getInventory() != null) {
            details.setStockQuantity(product.getInventory().getStockQuantity());
            details.setWarehouseLocation(product.getInventory().getWarehouseLocation());
        }
        if (descriptionOpt.isPresent()) {
            ProductDescription desc = descriptionOpt.get();
            details.setDetailedDescription(desc.getDetailedDescription());
            details.setFeatures(desc.getFeatures());
            details.setSpecifications(desc.getSpecifications());
        }
        return details;
    }

    public ProductService(final ProductRepository productRepository, final ProductDescriptionRepository productDescriptionRepository, final ProductMapper productMapper) {
        this.productRepository = productRepository;
        this.productDescriptionRepository = productDescriptionRepository;
        this.productMapper = productMapper;
    }
}
