// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.service;

import com.productcatalog.app.dto.SearchRequestDTO;
import com.productcatalog.app.mongo.UserSearchLog;
import com.productcatalog.app.mongo.UserSearchLogRepository;
import org.bson.Document;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.stereotype.Service;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Service
public class ProductSearchService {
    private final MongoTemplate mongoTemplate;
    private final UserSearchLogRepository userSearchLogRepository;

    public List<Document> semanticSearch(SearchRequestDTO requestDTO) {
        // 1. Generate Embedding for the query (Mocking for now, in a real scenario you'd call an LLM API like OpenAI or HuggingFace)
        List<Double> queryEmbedding = generateMockEmbedding(requestDTO.getQuery());
        // 2. Build MongoDB Vector Search Aggregation Pipeline
        Document vectorSearchCommand = new Document("$vectorSearch", new Document("index", "vector_index").append("path", "embedding").append("queryVector", queryEmbedding).append("numCandidates", 100).append("limit", 10));
        Document projectCommand = new Document("$project",  // Exclude the raw embedding vector from results
        new Document("embedding", 0).append("score", new Document("$meta", "vectorSearchScore")));
        List<Document> pipeline = Arrays.asList(vectorSearchCommand, projectCommand);
        // 3. Execute Aggregation
        List<Document> results = new ArrayList<>();
        mongoTemplate.getCollection("product_embeddings").aggregate(pipeline).into(results);
        // 4. Log the search
        logSearch(requestDTO.getQuery(), results.size());
        return results;
    }

    private void logSearch(String query, int resultCount) {
        UserSearchLog log = UserSearchLog.builder().query(query).searchTime(LocalDateTime.now()).resultCount(resultCount).build();
        userSearchLogRepository.save(log);
    }

    /**
     * In a real application, you would pass the query string to an embedding API 
     * (like OpenAI's text-embedding-ada-002) to get the actual vector.
     */
    private List<Double> generateMockEmbedding(String query) {
        // Return a mock vector of 384 dimensions (e.g. typical for all-MiniLM-L6-v2)
        List<Double> vector = new ArrayList<>();
        for (int i = 0; i < 384; i++) {
            vector.add(Math.random());
        }
        return vector;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductSearchService(final MongoTemplate mongoTemplate, final UserSearchLogRepository userSearchLogRepository) {
        this.mongoTemplate = mongoTemplate;
        this.userSearchLogRepository = userSearchLogRepository;
    }
}
