// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.dto;

import java.math.BigDecimal;

public class ProductDetailsDTO {
    // PostgreSQL Data
    private Long id;
    private String name;
    private String brand;
    private String sku;
    private String categoryName;
    private BigDecimal basePrice;
    private BigDecimal discountPrice;
    private String currency;
    private Integer stockQuantity;
    private String warehouseLocation;
    // MongoDB Data
    private String detailedDescription;
    private String features;
    private String specifications;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ProductDetailsDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String brand;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String sku;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String categoryName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal basePrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal discountPrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String currency;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer stockQuantity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String warehouseLocation;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String detailedDescription;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String features;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String specifications;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ProductDetailsDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder brand(final String brand) {
            this.brand = brand;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder sku(final String sku) {
            this.sku = sku;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder categoryName(final String categoryName) {
            this.categoryName = categoryName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder basePrice(final BigDecimal basePrice) {
            this.basePrice = basePrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder discountPrice(final BigDecimal discountPrice) {
            this.discountPrice = discountPrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder stockQuantity(final Integer stockQuantity) {
            this.stockQuantity = stockQuantity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder warehouseLocation(final String warehouseLocation) {
            this.warehouseLocation = warehouseLocation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder detailedDescription(final String detailedDescription) {
            this.detailedDescription = detailedDescription;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder features(final String features) {
            this.features = features;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO.ProductDetailsDTOBuilder specifications(final String specifications) {
            this.specifications = specifications;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProductDetailsDTO build() {
            return new ProductDetailsDTO(this.id, this.name, this.brand, this.sku, this.categoryName, this.basePrice, this.discountPrice, this.currency, this.stockQuantity, this.warehouseLocation, this.detailedDescription, this.features, this.specifications);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ProductDetailsDTO.ProductDetailsDTOBuilder(id=" + this.id + ", name=" + this.name + ", brand=" + this.brand + ", sku=" + this.sku + ", categoryName=" + this.categoryName + ", basePrice=" + this.basePrice + ", discountPrice=" + this.discountPrice + ", currency=" + this.currency + ", stockQuantity=" + this.stockQuantity + ", warehouseLocation=" + this.warehouseLocation + ", detailedDescription=" + this.detailedDescription + ", features=" + this.features + ", specifications=" + this.specifications + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ProductDetailsDTO.ProductDetailsDTOBuilder builder() {
        return new ProductDetailsDTO.ProductDetailsDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBrand() {
        return this.brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSku() {
        return this.sku;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategoryName() {
        return this.categoryName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDiscountPrice() {
        return this.discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStockQuantity() {
        return this.stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWarehouseLocation() {
        return this.warehouseLocation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDetailedDescription() {
        return this.detailedDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFeatures() {
        return this.features;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSpecifications() {
        return this.specifications;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBrand(final String brand) {
        this.brand = brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSku(final String sku) {
        this.sku = sku;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryName(final String categoryName) {
        this.categoryName = categoryName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBasePrice(final BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiscountPrice(final BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStockQuantity(final Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWarehouseLocation(final String warehouseLocation) {
        this.warehouseLocation = warehouseLocation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDetailedDescription(final String detailedDescription) {
        this.detailedDescription = detailedDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFeatures(final String features) {
        this.features = features;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecifications(final String specifications) {
        this.specifications = specifications;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProductDetailsDTO)) return false;
        final ProductDetailsDTO other = (ProductDetailsDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$stockQuantity = this.getStockQuantity();
        final java.lang.Object other$stockQuantity = other.getStockQuantity();
        if (this$stockQuantity == null ? other$stockQuantity != null : !this$stockQuantity.equals(other$stockQuantity)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$brand = this.getBrand();
        final java.lang.Object other$brand = other.getBrand();
        if (this$brand == null ? other$brand != null : !this$brand.equals(other$brand)) return false;
        final java.lang.Object this$sku = this.getSku();
        final java.lang.Object other$sku = other.getSku();
        if (this$sku == null ? other$sku != null : !this$sku.equals(other$sku)) return false;
        final java.lang.Object this$categoryName = this.getCategoryName();
        final java.lang.Object other$categoryName = other.getCategoryName();
        if (this$categoryName == null ? other$categoryName != null : !this$categoryName.equals(other$categoryName)) return false;
        final java.lang.Object this$basePrice = this.getBasePrice();
        final java.lang.Object other$basePrice = other.getBasePrice();
        if (this$basePrice == null ? other$basePrice != null : !this$basePrice.equals(other$basePrice)) return false;
        final java.lang.Object this$discountPrice = this.getDiscountPrice();
        final java.lang.Object other$discountPrice = other.getDiscountPrice();
        if (this$discountPrice == null ? other$discountPrice != null : !this$discountPrice.equals(other$discountPrice)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        final java.lang.Object this$warehouseLocation = this.getWarehouseLocation();
        final java.lang.Object other$warehouseLocation = other.getWarehouseLocation();
        if (this$warehouseLocation == null ? other$warehouseLocation != null : !this$warehouseLocation.equals(other$warehouseLocation)) return false;
        final java.lang.Object this$detailedDescription = this.getDetailedDescription();
        final java.lang.Object other$detailedDescription = other.getDetailedDescription();
        if (this$detailedDescription == null ? other$detailedDescription != null : !this$detailedDescription.equals(other$detailedDescription)) return false;
        final java.lang.Object this$features = this.getFeatures();
        final java.lang.Object other$features = other.getFeatures();
        if (this$features == null ? other$features != null : !this$features.equals(other$features)) return false;
        final java.lang.Object this$specifications = this.getSpecifications();
        final java.lang.Object other$specifications = other.getSpecifications();
        if (this$specifications == null ? other$specifications != null : !this$specifications.equals(other$specifications)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProductDetailsDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $stockQuantity = this.getStockQuantity();
        result = result * PRIME + ($stockQuantity == null ? 43 : $stockQuantity.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $brand = this.getBrand();
        result = result * PRIME + ($brand == null ? 43 : $brand.hashCode());
        final java.lang.Object $sku = this.getSku();
        result = result * PRIME + ($sku == null ? 43 : $sku.hashCode());
        final java.lang.Object $categoryName = this.getCategoryName();
        result = result * PRIME + ($categoryName == null ? 43 : $categoryName.hashCode());
        final java.lang.Object $basePrice = this.getBasePrice();
        result = result * PRIME + ($basePrice == null ? 43 : $basePrice.hashCode());
        final java.lang.Object $discountPrice = this.getDiscountPrice();
        result = result * PRIME + ($discountPrice == null ? 43 : $discountPrice.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        final java.lang.Object $warehouseLocation = this.getWarehouseLocation();
        result = result * PRIME + ($warehouseLocation == null ? 43 : $warehouseLocation.hashCode());
        final java.lang.Object $detailedDescription = this.getDetailedDescription();
        result = result * PRIME + ($detailedDescription == null ? 43 : $detailedDescription.hashCode());
        final java.lang.Object $features = this.getFeatures();
        result = result * PRIME + ($features == null ? 43 : $features.hashCode());
        final java.lang.Object $specifications = this.getSpecifications();
        result = result * PRIME + ($specifications == null ? 43 : $specifications.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ProductDetailsDTO(id=" + this.getId() + ", name=" + this.getName() + ", brand=" + this.getBrand() + ", sku=" + this.getSku() + ", categoryName=" + this.getCategoryName() + ", basePrice=" + this.getBasePrice() + ", discountPrice=" + this.getDiscountPrice() + ", currency=" + this.getCurrency() + ", stockQuantity=" + this.getStockQuantity() + ", warehouseLocation=" + this.getWarehouseLocation() + ", detailedDescription=" + this.getDetailedDescription() + ", features=" + this.getFeatures() + ", specifications=" + this.getSpecifications() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductDetailsDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductDetailsDTO(final Long id, final String name, final String brand, final String sku, final String categoryName, final BigDecimal basePrice, final BigDecimal discountPrice, final String currency, final Integer stockQuantity, final String warehouseLocation, final String detailedDescription, final String features, final String specifications) {
        this.id = id;
        this.name = name;
        this.brand = brand;
        this.sku = sku;
        this.categoryName = categoryName;
        this.basePrice = basePrice;
        this.discountPrice = discountPrice;
        this.currency = currency;
        this.stockQuantity = stockQuantity;
        this.warehouseLocation = warehouseLocation;
        this.detailedDescription = detailedDescription;
        this.features = features;
        this.specifications = specifications;
    }
}
