// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.dto;

import java.math.BigDecimal;

public class ProductFilterRequestDTO {
    private String category;
    private String brand;
    private BigDecimal minPrice;
    private BigDecimal maxPrice;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProductFilterRequestDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBrand() {
        return this.brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getMinPrice() {
        return this.minPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getMaxPrice() {
        return this.maxPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBrand(final String brand) {
        this.brand = brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMinPrice(final BigDecimal minPrice) {
        this.minPrice = minPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMaxPrice(final BigDecimal maxPrice) {
        this.maxPrice = maxPrice;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProductFilterRequestDTO)) return false;
        final ProductFilterRequestDTO other = (ProductFilterRequestDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$brand = this.getBrand();
        final java.lang.Object other$brand = other.getBrand();
        if (this$brand == null ? other$brand != null : !this$brand.equals(other$brand)) return false;
        final java.lang.Object this$minPrice = this.getMinPrice();
        final java.lang.Object other$minPrice = other.getMinPrice();
        if (this$minPrice == null ? other$minPrice != null : !this$minPrice.equals(other$minPrice)) return false;
        final java.lang.Object this$maxPrice = this.getMaxPrice();
        final java.lang.Object other$maxPrice = other.getMaxPrice();
        if (this$maxPrice == null ? other$maxPrice != null : !this$maxPrice.equals(other$maxPrice)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProductFilterRequestDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $brand = this.getBrand();
        result = result * PRIME + ($brand == null ? 43 : $brand.hashCode());
        final java.lang.Object $minPrice = this.getMinPrice();
        result = result * PRIME + ($minPrice == null ? 43 : $minPrice.hashCode());
        final java.lang.Object $maxPrice = this.getMaxPrice();
        result = result * PRIME + ($maxPrice == null ? 43 : $maxPrice.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ProductFilterRequestDTO(category=" + this.getCategory() + ", brand=" + this.getBrand() + ", minPrice=" + this.getMinPrice() + ", maxPrice=" + this.getMaxPrice() + ")";
    }
}
