// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;

@Entity
@Table(name = "pricing")
public class Pricing {
    @Id
    private Long productId;
    @OneToOne
    @MapsId
    @JoinColumn(name = "product_id")
    private Product product;
    @Column(nullable = false)
    private BigDecimal basePrice;
    private BigDecimal discountPrice;
    @Column(nullable = false)
    private String currency;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PricingBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long productId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Product product;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal basePrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal discountPrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String currency;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PricingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Pricing.PricingBuilder productId(final Long productId) {
            this.productId = productId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Pricing.PricingBuilder product(final Product product) {
            this.product = product;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Pricing.PricingBuilder basePrice(final BigDecimal basePrice) {
            this.basePrice = basePrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Pricing.PricingBuilder discountPrice(final BigDecimal discountPrice) {
            this.discountPrice = discountPrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Pricing.PricingBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Pricing build() {
            return new Pricing(this.productId, this.product, this.basePrice, this.discountPrice, this.currency);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Pricing.PricingBuilder(productId=" + this.productId + ", product=" + this.product + ", basePrice=" + this.basePrice + ", discountPrice=" + this.discountPrice + ", currency=" + this.currency + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Pricing.PricingBuilder builder() {
        return new Pricing.PricingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getProductId() {
        return this.productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDiscountPrice() {
        return this.discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductId(final Long productId) {
        this.productId = productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProduct(final Product product) {
        this.product = product;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBasePrice(final BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiscountPrice(final BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Pricing() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Pricing(final Long productId, final Product product, final BigDecimal basePrice, final BigDecimal discountPrice, final String currency) {
        this.productId = productId;
        this.product = product;
        this.basePrice = basePrice;
        this.discountPrice = discountPrice;
        this.currency = currency;
    }
}
