// Generated by delombok at Sat Jun 13 23:26:02 IST 2026
package com.productcatalog.app.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "products")
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    private String brand;
    private String sku;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;
    @OneToOne(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Pricing pricing;
    @OneToOne(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Inventory inventory;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ProductBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String brand;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String sku;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Category category;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Pricing pricing;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Inventory inventory;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ProductBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product.ProductBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product.ProductBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product.ProductBuilder brand(final String brand) {
            this.brand = brand;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product.ProductBuilder sku(final String sku) {
            this.sku = sku;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product.ProductBuilder category(final Category category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product.ProductBuilder pricing(final Pricing pricing) {
            this.pricing = pricing;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product.ProductBuilder inventory(final Inventory inventory) {
            this.inventory = inventory;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Product build() {
            return new Product(this.id, this.name, this.brand, this.sku, this.category, this.pricing, this.inventory);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Product.ProductBuilder(id=" + this.id + ", name=" + this.name + ", brand=" + this.brand + ", sku=" + this.sku + ", category=" + this.category + ", pricing=" + this.pricing + ", inventory=" + this.inventory + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Product.ProductBuilder builder() {
        return new Product.ProductBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBrand() {
        return this.brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSku() {
        return this.sku;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Category getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Pricing getPricing() {
        return this.pricing;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Inventory getInventory() {
        return this.inventory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBrand(final String brand) {
        this.brand = brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSku(final String sku) {
        this.sku = sku;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final Category category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPricing(final Pricing pricing) {
        this.pricing = pricing;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInventory(final Inventory inventory) {
        this.inventory = inventory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Product() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Product(final Long id, final String name, final String brand, final String sku, final Category category, final Pricing pricing, final Inventory inventory) {
        this.id = id;
        this.name = name;
        this.brand = brand;
        this.sku = sku;
        this.category = category;
        this.pricing = pricing;
        this.inventory = inventory;
    }
}
